name: "Setup Nix"
description: "Install Nix and configure Cachix"
inputs:
  cachix-auth-token:
    description: "Cachix authentication token"
    required: false
runs:
  using: "composite"
  steps:
    - name: Install Nix
      uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ github.token }}

    - name: Setup Cachix (ryoppippi)
      uses: cachix/cachix-action@v16
      with:
        name: ryoppippi
        authToken: ${{ inputs.cachix-auth-token }}
